id: Google Kubernetes Engine Operations Generic Polling
version: -1
name: Google Kubernetes Engine Operations Generic Polling
description: This playbook check operations status in Google Kubernetes Engine, Will
  run until operation from argument will finish, This will allow waiting between steps
  in Cluster configuration.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5dd677b4-0ada-4274-8434-420da4c46b87
    type: start
    task:
      id: 5dd677b4-0ada-4274-8434-420da4c46b87
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 23e0eb54-9afd-4a19-83aa-b413b5cfa2b9
    type: playbook
    task:
      id: 23e0eb54-9afd-4a19-83aa-b413b5cfa2b9
      version: -1
      name: Generic Polling - Active operations
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: project,zone
      AdditionalPollingCommandArgValues:
        simple: ${inputs.project},${inputs.zone}
      Ids:
        simple: ${inputs.operation}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: operation
      PollingCommandName:
        simple: gcloud-operations-describe
      Timeout:
        simple: "30"
      dt:
        simple: GKE.Operation(val.Status && val.Status == 'RUNNING').Status
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 67ccbced-3b5e-411b-869f-c6433aba34bf
    type: regular
    task:
      id: 67ccbced-3b5e-411b-869f-c6433aba34bf
      version: -1
      name: Print
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      value:
        simple: 'No operations run in Google Kubernetes engine - Project: ${inputs.project},  Zone:${inputs.zone}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: a81d0d38-76ff-43aa-804a-3dcc9ba2bf05
    type: title
    task:
      id: a81d0d38-76ff-43aa-804a-3dcc9ba2bf05
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: project
  value: {}
  required: true
  description: The Google Developers Console project ID or project number.
  playbookInputQuery: null
- key: zone
  value: {}
  required: true
  description: The name of the Google Compute Engine zone in which the cluster resides.
  playbookInputQuery: null
- key: cluster
  value: {}
  required: true
  description: The name of the cluster to check if in the state running.
  playbookInputQuery: null
- key: operation
  value: {}
  required: false
  description: Operation name.
  playbookInputQuery: null
outputs:
- type: unknown
